# Generated by Django 6.0.3 on 2026-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='heyzine_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
