# Generated by Django 6.0.3 on 2026-04-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flipbook_heyzine_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationvideo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archived'), ('restore', 'Restored'), ('login', 'Logged in'), ('logout', 'Logged out'), ('register', 'Registered')], max_length=20),
        ),
    ]
