# Generated by Django 6.0.3 on 2026-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationvideo',
            name='grade',
            field=models.CharField(choices=[('All Grades', 'All Grades'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], default='All Grades', max_length=20),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='grade',
            field=models.CharField(choices=[('All Grades', 'All Grades'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], default='All Grades', max_length=20),
        ),
    ]
