# Generated by Django 6.0.3 on 2026-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_animationvideo_grade_flipbook_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationvideo',
            name='craft_category',
            field=models.CharField(choices=[('All Categories', 'All Categories'), ('Toys & Games', 'Toys & Games (DIY PLAY)'), ('Role play & Imagination', 'Role play & Imagination'), ('Simple Science & Experiments', 'Simple Science & Experiments'), ('Home & Classroom decoration', 'Home & Classroom decoration'), ('Art & Creative crafts', 'Art & Creative crafts'), ('Paper & cardboard crafts', 'Paper & cardboard crafts'), ('Health & Hygiene', 'Health & Hygiene'), ('Nature & Eco - Friendly projects', 'Nature & Eco - Friendly projects'), ('Gifts & Holiday crafts', 'Gifts & Holiday crafts'), ('Skill - Building crafts', 'Skill - Building crafts')], default='All Categories', max_length=50),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='craft_category',
            field=models.CharField(choices=[('All Categories', 'All Categories'), ('Toys & Games', 'Toys & Games (DIY PLAY)'), ('Role play & Imagination', 'Role play & Imagination'), ('Simple Science & Experiments', 'Simple Science & Experiments'), ('Home & Classroom decoration', 'Home & Classroom decoration'), ('Art & Creative crafts', 'Art & Creative crafts'), ('Paper & cardboard crafts', 'Paper & cardboard crafts'), ('Health & Hygiene', 'Health & Hygiene'), ('Nature & Eco - Friendly projects', 'Nature & Eco - Friendly projects'), ('Gifts & Holiday crafts', 'Gifts & Holiday crafts'), ('Skill - Building crafts', 'Skill - Building crafts')], default='All Categories', max_length=50),
        ),
    ]
