# Generated by Django 6.0.3 on 2026-04-29 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_animationvideo_likes_flipbook_likes_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animationvideo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='flipbook',
            name='likes',
        ),
        migrations.AddField(
            model_name='animationvideo',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flipbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
