# Generated by Django 6.0.3 on 2026-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_flipbookcomment_videocomment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Star', max_length=50)),
                ('required_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='flipbook',
            name='heyzine_url',
        ),
        migrations.AddField(
            model_name='animationvideo',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='animationvideo',
            name='requires_supervision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='requires_supervision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flipbookcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='main.badge'),
        ),
    ]
