# Generated by Django 6.0.3 on 2026-05-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_badge_remove_flipbook_heyzine_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='animationvideo',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='animationvideo',
            name='requires_supervision',
        ),
        migrations.RemoveField(
            model_name='flipbook',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='flipbook',
            name='requires_supervision',
        ),
        migrations.RemoveField(
            model_name='flipbookcomment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='is_approved',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
