# Generated by Django 6.0.3 on 2026-05-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_badge_userprofile_points_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
