# Generated by Django 6.0.3 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_userbadge_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
