# Generated by Django 6.0.3 on 2026-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_studentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
