# Generated by Django 6.0.3 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_announcement_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lrn_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
