# Generated by Django 6.0.3 on 2026-05-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_notifications',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
