# Generated by Django 6.0.3 on 2026-05-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userprofile_last_seen_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faculty_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_ids/'),
        ),
    ]
