# Generated by Django 6.0.3 on 2026-05-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_userprofile_faculty_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Holiday', 'Holiday'), ('Lesson Plan', 'Lesson Plan'), ('Module', 'Module'), ('Other', 'Other')], default='Event', max_length=20),
        ),
    ]
