# Generated by Django 6.0.3 on 2026-05-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_teachertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_grade',
            field=models.CharField(blank=True, choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=20, null=True),
        ),
    ]
