# Generated by Django 6.0.3 on 2026-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_userprofile_pending_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade_change_cooldown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
