# Generated by Django 6.0.3 on 2026-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_userprofile_grade_change_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Update', 'Update'), ('Activity', 'Activity'), ('Event', 'Event')], default='Update', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
