# Generated by Django 6.0.3 on 2026-05-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
