# Generated by Django 6.0.3 on 2026-05-19 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
