# Generated by Django 6.0.3 on 2026-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_announcement_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Update', 'Update'), ('Activity', 'Activity'), ('Event', 'Event'), ('Holiday', 'Holiday')], default='Update', max_length=20),
        ),
    ]
