# Generated by Django 6.0.3 on 2026-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('All', 'All'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='All', max_length=20),
        ),
    ]
