# Generated by Django 6.0.3 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_announcement_target_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('All', 'All'), ('Teacher', 'Teacher')], default='All', max_length=20),
        ),
    ]
