# Generated by Django 6.0.3 on 2026-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_notification_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Holiday', 'Holiday'), ('Lesson Plan', 'Lesson Plan'), ('Module', 'Module'), ('Other', 'Other'), ('Todo', 'Todo'), ('Working On', 'Working On'), ('Stuck', 'Stuck'), ('Done', 'Done')], default='Event', max_length=20),
        ),
    ]
